from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("8.10.0")

##### setup report #####
configfile: "config/config.yaml"

##### load rules #####
include: "rules/common.smk"
include: "rules/preprocessing.smk"
include: "rules/calling.smk"

rule all:
    input:
        expand(
            resolve_results_filepath('reads',
                "{sample}.cram"),
            sample=samples['sample'],
        ),
        expand(
            resolve_results_filepath('reads',
                "{sample}.cram.crai"),
            sample=samples['sample'],
        ),
        expand(
            resolve_results_filepath('calling',
                "{sample}/{sample}.vcf.gz"),
            sample=samples['sample'],
        ),