from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("8.10.0")

##### setup report #####
configfile: "config/config.yaml"

##### load rules #####
include: "rules/common.smk"
include: "rules/preprocessing.smk"
include: "rules/metrics.smk"
include: "rules/calling.smk"
include: "rules/annotation.smk"
include: "rules/delivery.smk"

rule all:
    input:
        expand(
            resolve_results_filepath('reads',
                "{sample}.bam"),
            sample=samples['sample'],
        ),
        expand(
            resolve_results_filepath('reads',
                "{sample}.bam.bai"),
            sample=samples['sample'],
        ),
        expand(
            resolve_results_filepath('metrics',
                "{sample}.hsmetrics.dat"),
            sample=samples['sample'],
        ),
        expand(
            resolve_results_filepath('calling',
                "{sample}/{sample}.vcf.gz"),
            sample=samples['sample'],
        ),
        expand(
            resolve_results_filepath('annotation',
                "{sample}/{sample}.annotated.vcf"),
            sample=samples['sample'],
        ),
        expand(
            resolve_results_filepath('annotation',
                "{sample}/{sample}.annotated.tsv"),
            sample=samples['sample'],
        ),
        expand(
            resolve_results_filepath('delivery',
                "{Client}/{Client}.bam"),
            Client=reheader.reset_index().itertuples(),
        )
