samples: config/samples.tsv
units: config/units.tsv
reheader: config/reheader.tsv

paths:
    workdir: "/path/to/workdir"
    results_dir: "/path/to/results_dir"

resources:
    reference: "/path/to/reference/reference_genome.fasta"
    regions: "/path/to/reference/regions.bed"

params:
  deepVariant:
    model_type: "WES"  # options [WGS,WES,PACBIO,ONT_R104,HYBRID_PACBIO_ILLUMINA]
  vep:
    resources: "/path/to/vep_resources"
    reference_version: "hg19" # options [hg19,hg38] or [GRCh37, GRCh38]
    cache_version: "106"
